# Generated by Django 3.0.8 on 2020-08-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200827_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='Cover',
        ),
    ]
