# Generated by Django 3.0.8 on 2020-09-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200827_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Cover',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
